"""add system_setting table

Revision ID: 7acdb3131e27
Revises: 0998c6215403
Create Date: 2026-01-14 22:33:45.192129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acdb3131e27'
down_revision = '0998c6215403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('workflow_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_escalated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_request', schema=None) as batch_op:
        batch_op.drop_column('is_escalated')

    op.drop_table('system_setting')
    # ### end Alembic commands ###
